on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  setup-build-publish-deploy:
    name: Build & deploy container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Student-service Jar archive
        uses: robinraju/release-downloader@v1.7
        with:
          repository: "UniStudents/student-service"
          latest: true
          fileName: "student-service-full.jar"
          token: ${{ secrets.GH_TOK }}
      - name: Download eLearning-service Jar archive
        uses: robinraju/release-downloader@v1.7
        with:
          repository: "UniStudents/elearning-service"
          latest: true
          fileName: "elearning-service-full.jar"
          token: ${{ secrets.GH_TOK }}
      - run: find ./libs -name "student-*.jar" -exec cp student-service-full.jar {} \;
      - run: find ./libs -name "elearning-*.jar" -exec cp elearning-service-full.jar {} \;

      - id: auth
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0.4.0"
        with:
          workload_identity_provider: "projects/1095653786209/locations/global/workloadIdentityPools/automations/providers/github"
          service_account: "github-actions@unistudents-faa49.iam.gserviceaccount.com"

      - name: Upload source code and build the image
        run: gcloud builds submit --suppress-logs --pack image=europe-west1-docker.pkg.dev/unistudents-faa49/unistudents-api/unistudents-api

      - name: Tag the latest commit
        run: gcloud artifacts docker tags add $(gcloud artifacts docker images list europe-west1-docker.pkg.dev/unistudents-faa49/unistudents-api/unistudents-api --filter="package=europe-west1-docker.pkg.dev/unistudents-faa49/unistudents-api/unistudents-api" --sort-by="~UPDATE_TIME" --limit=1 --format="value(format("{0}@{1}",package,version))") $(gcloud artifacts docker images list europe-west1-docker.pkg.dev/unistudents-faa49/unistudents-api/unistudents-api/ --filter="package=europe-west1-docker.pkg.dev/unistudents-faa49/unistudents-api/unistudents-api" --sort-by="~UPDATE_TIME" --limit=1 --format="value(format("{0}",package))"):$GITHUB_SHA
