on:
  push:
    branches:
      - lib-implementation
  workflow_dispatch:

jobs:
  setup-build-publish-deploy:
    name: Build & deploy container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Student-service Jar archive
        uses: robinraju/release-downloader@v1.7
        with:
          repository: "UniStudents/student-service"
          latest: true
          fileName: "student-service-full.jar"
          token: ${{ secrets.GH_TOK }}
      - name: Download eLearning-service Jar archive
        uses: robinraju/release-downloader@v1.7
        with:
          repository: "UniStudents/elearning-service"
          latest: true
          fileName: "elearning-service-full.jar"
          token: ${{ secrets.GH_TOK }}
      - run: find ./libs -name "student-*.jar" -exec cp student-service-full.jar {} \;
      - run: find ./libs -name "elearning-*.jar" -exec cp elearning-service-full.jar {} \;
      - name: Setup
        id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

      - run: gcloud run deploy unistudents-api --region=europe-west1 --source="./" > /dev/null
